
const topics=
[
    {
        "topic": "Countries",
        "language": "english",
        "words": [
            "UK",
            "France",
            "Germany",
            "Canada",
            "Spain",
            "USA",
            "Mexico",
            "China",
            "Japan",
            "Italy",
            "India",
            "Russia",
            "Brazil",
            "Australia",
            "Israel",
            "Egypt"
        ]
    },
    {
        "topic": "Movies",
        "language": "english",
        "words": [
            "Jurassic Park",
            "Transformers",
            "E.T.",
            "Shrek",
            "Jaws",
            "Toy Story",
            "The Wizard of Oz",
            "The Godfather",
            "Raiders of the Lost Ark",
            "Home Alone",
            "King Kong",
            "Finding Nemo",
            "The Avengers",
            "Titanic",
            "The Matrix",
            "Avatar"
        ]
    },
    {
        "topic": "Inventions",
        "language": "english",
        "words": [
            "Matches",
            "Computer",
            "TV",
            "Car",
            "Gunpowder",
            "Internet",
            "Electricity",
            "Telephone",
            "Wheel",
            "Compass",
            "Writing",
            "Camera",
            "Printing",
            "Plane",
            "Steam Engine",
            "Radio"
        ]
    },
    {
        "topic": "Hobbies",
        "language": "english",
        "words": [
            "Stamps",
            "Fishing",
            "Sailing",
            "Cooking",
            "Trains",
            "Reading",
            "Travel",
            "Yoga",
            "Model Making",
            "Painting",
            "Walking",
            "Photography",
            "Knitting",
            "Gardening",
            "Pottery",
            "Hiking"
        ]
    },
    {
        "topic": "Musicals",
        "language": "english",
        "words": [
            "West Side Story",
            "Phantom of the Opera",
            "Chicago",
            "Lion King",
            "Cats",
            "Les Misérables",
            "42nd Street",
            "Wicked",
            "Jersey Boys",
            "Oliver",
            "Annie",
            "Hairspray",
            "School of Rock",
            "Hamilton",
            "Book of Mormon",
            "Mamma Mia"
        ]
    },
    {
        "topic": "Sports",
        "language": "english",
        "words": [
            "Football",
            "Basketball",
            "Tennis",
            "Poker",
            "Soccer",
            "Ice Hockey",
            "Badminton",
            "Volleyball",
            "Golf",
            "Sailing",
            "Motor Racing",
            "Table Tennis",
            "Baseball",
            "Chess",
            "Wrestling",
            "Cycling"
        ]
    },
    {
        "topic": "The Arts",
        "language": "english",
        "words": [
            "Painting",
            "Sculpture",
            "Architecture",
            "Dance",
            "Literature",
            "Opera",
            "Stand-up",
            "Comic Books",
            "Illustration",
            "Music",
            "Theatre",
            "Cinema",
            "Video Games",
            "Graffiti",
            "Fashion",
            "Photography"
        ]
    },
    {
        "topic": "Under the Sea",
        "language": "english",
        "words": [
            "Octopus",
            "Lobster",
            "Crab",
            "Sea Turtle",
            "Starfish",
            "Seal",
            "Giant Squid",
            "Clownfish",
            "Shark",
            "Dolphin",
            "Seahorse",
            "Swordfish",
            "Jellyfish",
            "Killer Whale",
            "Stingray",
            "Mermaid"
        ]
    },
    {
        "topic": "Rooms",
        "language": "english",
        "words": [
            "Kitchen",
            "Bathroom",
            "Attic",
            "Den",
            "Hallway",
            "Dining Room",
            "Basement",
            "Bunker",
            "Greenhouse",
            "Office",
            "Porch",
            "Shed",
            "Bedroom",
            "Living Room",
            "Nursery",
            "Garage"
        ]
    },
    {
        "topic": "Phobias",
        "language": "english",
        "words": [
            "Ghosts",
            "Toilets",
            "Needles",
            "Children",
            "Spiders",
            "Snakes",
            "Dogs",
            "Shadows",
            "Monsters",
            "Germs",
            "Birds",
            "Roller Coasters",
            "Rats",
            "Clowns",
            "Insects",
            "Planes"
        ]
    },
    {
        "topic": "Drinks",
        "language": "english",
        "words": [
            "Coffee",
            "Wine",
            "Hot Chocolate",
            "Smoothie",
            "Tea",
            "Beer",
            "Milkshake",
            "Orange Juice",
            "Lemonade",
            "Punch",
            "Root Beer",
            "Milk",
            "Coca-Cola",
            "Tequila",
            "Water",
            "Champagne"
        ]
    },
    {
        "topic": "Geography",
        "language": "english",
        "words": [
            "Lake",
            "River",
            "Jungle",
            "Volcano",
            "Sea",
            "Desert",
            "Island",
            "Cave",
            "Valley",
            "Ocean",
            "Glacier",
            "Arctic",
            "Mountain",
            "Forest",
            "Waterfall",
            "Swamp"
        ]
    },
    {
        "topic": "Film Genres",
        "language": "english",
        "words": [
            "Horror",
            "Rom-Com",
            "Gangster",
            "Musical",
            "Action",
            "Western",
            "Foreign Language",
            "Animation",
            "Thriller",
            "Comedy",
            "War",
            "Zombie",
            "Sci-Fi",
            "Christmas",
            "Documentary",
            "Sport"
        ]
    },
    {
        "topic": "Jobs",
        "language": "english",
        "words": [
            "Fisherman",
            "Janitor",
            "Truck Driver",
            "Police Officer",
            "Lumberjack",
            "Secretary",
            "Security Guard",
            "Lawyer",
            "Nurse",
            "Accountant",
            "Chef",
            "Carpenter",
            "Waiter",
            "Teacher",
            "Architect",
            "Butcher"
        ]
    },
    {
        "topic": "Food",
        "language": "english",
        "words": [
            "Pizza",
            "Pasta",
            "Eggs",
            "Sausage",
            "Potatoes",
            "Salad",
            "Cheese",
            "Ice Cream",
            "Fish",
            "Soup",
            "Fruit",
            "Chocolate",
            "Cake",
            "Bread",
            "Chicken",
            "Beef"
        ]
    },
    {
        "topic": "School",
        "language": "english",
        "words": [
            "Math",
            "History",
            "Economics",
            "Gym",
            "Chemistry",
            "Philosophy",
            "Spanish",
            "Latin",
            "Physics",
            "Geography",
            "Art",
            "Religion",
            "Biology",
            "English",
            "Music",
            "Technology"
        ]
    },
    {
        "topic": "Zoo",
        "language": "english",
        "words": [
            "Scorpion",
            "Ostrich",
            "Lion",
            "Elephant",
            "Giraffe",
            "Leopard",
            "Owl",
            "Alligator",
            "Koala",
            "Meerkat",
            "Eagle",
            "Zebra",
            "Tiger",
            "Buffalo",
            "Parrot",
            "Gorilla"
        ]
    }
]

exports.topics = topics;
